package com.example.wisescan.navigation

const val LOGIN = "login"
const val DASHBOARD = "dashboard"
const val SIGNUP = "signup"
const val FORGOT_PASSWORD = "forgot_password"
const val SETTINGS= "settings"
const val ACCOUNT_SETTINGS= "account_settings"
const val ABOUT= "about"
const val LANGUAGE_SELECT= "language selection"
const val CAPTURE_SCREEN= "capture screen"
const val CAMERA_ANALYSIS= "camera  analysis"
const val PERSONALIZED_ANALYSIS= "personalized analysis"
const val PERSONALIZED_CONTENT= "personalized content"
const val SOCIALIZE= "socialize"
const val TRAIN_AI= "train ai"
const val COLLECTIVE_ANALYSIS= "collective analysis"
const val CAREER_PILOT= "collective analysis"
const val STORAGE= "storage"

