package com.example.wisescan.navigation

const val LOGIN = "login"
const val DASHBOARD = "dashboard"
const val SIGNUP = "signup"
const val FORGOT_PASSWORD = "forgot_password"
const val SETTINGS= "settings"
const val ACCOUNT_SETTINGS= "account_settings"
const val ABOUT= "about"
const val LANGUAGE_SELECT= "language selection"
const val CAPTURE_SCREEN= "capture screen"
const val PERSONALIZED_ANALYSIS= "personalized analysis"
const val PERSONALIZED_CONTENT= "personalized content"
const val SOCIALIZE= "socialize"
const val TRAIN_AI= "train ai"
const val GENERAL_ANALYSIS= "general analysis"
const val CAREER_PILOT= "collective analysis"
const val STORAGE= "storage"
const val SCANNED_AI_ANALYSIS= "scanned ai analysis"
const val SCANNED_DOCUMENTS= "scanned documents"
const val IMPORTANT_DATA= "important data"
const val RANDOM_DATA= "random data"
const val SAVED_AUDIOS= "saved audios"
const val SAVED_DOCUMENTS= "saved documents"
const val SAVED_VIDEOS= "saved videos"
const val SAVED_IMAGES= "saved images"

